sudo: required
language: java

services:
  - docker

env:
  global:
    - secure: "KjTXoNdRlQUh9bIW520Gu1S+tKzdGgnAmK1vzBacTB4dhzHDRStHLLN7PDuw9T7UiNIImREaq6FEY1OQX9M2DIR7tEc6ZULqmTDcHvrm4Eg78cmqhoDPxo2R9FY8f0vthpCeRZ8xFXip4YleLxhv2zRY9ssb+EQgMnZstbtZiLPoGXf+9ZWSLg+UrTg2pv7X6UlOLVJUPuYo6npBDu33FAFXmGvXJRNnbZzDqo0mAfHjOptu8W/qwRagTt4lTe6FIwTmG3bxqKVxfcKnTVzSW0lR7JQcRMupRzFLf5sE8hwE9wevbcxxplI75TEycRkQpMw65rieJFjLkxrNdftV1LqFGkACJP5SFxjbeGjDtM+Gxp4AWa253TBKFQs01UV6fLnsHX+xLI+O2xcgMFGLz1POOcd4/LRK7Mo3viYuA8ovx+756aMJr3MpOJqByeKebuabdWeAr/3vuN8tCw2L22Yk/2a9FUhLGb1JetIsk5Ce+GEvEjJc48arEVQ9pMme+ZTUJG5ik/beJCUozhjOjRk6GFBUd2RneEpFzdteJo0D+RsP+6kRWmMtH0Y066QsGreJQQLP84B3PsOB9nCfhzJRuHEMH4b0BcBgbVGSRLkbjoIpJA6VAq3K4zWvof4vSY6N9PZ/Dz/UJu0FS15BCRDX/YVEa4UTgCutMa/Zwww="
    - secure: "R+XwS7jeKfmXO/jEIcG00zPozcDoTvRuCMk7EbxyyazFp4KkvMZw1jBKjjzSEEwpYkcapR/NH/3uNpzilW6txpzqXhHTU5eZKnUSm/+5oR2IGCLIx8zTTIsPfm28F5uFnmtBofzOCGTwbrbPTeSEsrYj9nspzv63T7dCZoKrprpFJqkBxgDPL+QcEicpJ0/dVqrxi3i+1r9b5aiR4QaX9c6DVw/uMSj5vkvJV+DcoU+WjTor0VD35aRAQi0UkEMfpIetVv3TsDMIKUCjO0/uS9HJ8KxX8iHNrUWsA95FIMt7RwkgpnR/wmcuWttf8aXwDem+ElEFJHENpQg266aoexDSb/ShMUGwsfqcJYR2h1bz3kcBBrHUaGgl2tvRFGjqMLznTTlomQ98NRvAv21bvCOIya+xYey+rSfLlA5ZN5a5GDVyLnsRWs1U9fRU4U2gwSIdvKoxCBCsylT2XLzZgjyDHNXZqyDTZPjn9djBCTgU48m5VcP5fW0QxsufcSGdvOFIh5M6CtmMYC6sGUCSP127znjlVx4Rc0DZeHAw5GLvy1c4GN81zRbUfde0HAFgGB1teDAZ+knlaCoYUb2puNdU41T0HQT4pwVrWYt6vZUTfeFZ6Ezp0VciNz+whRccdtJcNJE8ExxAPg38xArnXaWlgKLXB+XSOyAaZtEp59w="
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - openssl aes-256-cbc -K $encrypted_a3c2492b5906_key -iv $encrypted_a3c2492b5906_iv -in gce.json.enc -out gce.json -d
  - chmod +x ./mvnw

jobs:
  include:
    - stage: test
      script: mvn clean verify
    - stage: build_docker
      script: docker build -t stocks .
    - stage: publish_docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag stocks $DOCKER_USERNAME/stocks:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/stocks:$TRAVIS_BUILD_NUMBER
        - docker tag stocks $DOCKER_USERNAME/stocks:latest
        - docker push $DOCKER_USERNAME/stocks:latest

deploy:
  provider: gae
  project: stocks-300020
  keyfile: gce.json
  verbosity: debug
  on: main