version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  docker: circleci/docker@1.5.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  maven_build:
    jobs:
      - maven/build
  docker_image_build:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true